kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    workload: system
    node.kubernetes.io/instance-type: kind
- role: worker
  labels:
    runtime: containerd-shim-spin
    node.kubernetes.io/instance-type: kind
