[package]
name = "hello-world"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "2.2.0"

[workspace]
