spin_manifest_version = 2

[application]
name = "password-hasher"
version = "0.1.0"
authors = ["Vaughn Dice <vaughn.dice@fermyon.com>"]
description = "A Spin app that calculates an argon2 password hash, with toggles for sleep, cpu, mem and password"

[[trigger.http]]
route = "/..."
component = "password-hasher"

[component.password-hasher]
source = "target/wasm32-wasi/release/cpu_mem_sleep.wasm"
allowed_outbound_hosts = []
[component.password-hasher.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
