[package]
name = "density-rust"
authors = ["Vaughn Dice <vaughn.dice@fermyon.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"

[workspace]
