name: Build and Push K6 Image
on:
  push:
    branches: [ main ]
    paths:
      - image/k6/Dockerfile
  workflow_dispatch:

env:
  REGISTRY_URL: spinkubeperf.azurecr.io

jobs:
  k6-image:
    name: Build and push k6 image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: image/k6
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY_URL }}/k6:latest
