name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-js:
    name: Test JS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: Run tests
        run: npm run test
