{
 "title": "SpinKube Performance Test Analysis",
 "time": { "from": "2024-07-24T22:22:10.303Z", "to": "2024-07-24T23:04:21.213Z" },
 "panels": [
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cores on Apps Node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(node) (machine_cpu_cores{node=~\"^aks-apps.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory of Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes /1000 /1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Language Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "50th Percentile HTTP Request Duration by Language",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(language) (histogram_quantile(0.5, rate(k6_http_req_duration_seconds{test_name=\"hello-world\"}[$__rate_interval]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage per Go Spin App (MB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"hello-world-go\"} / 1000 / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Seconds for Go Spin App",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{container=\"hello-world-go\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage per Python Spin App (MB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"hello-world-py\"} / 1000 / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Seconds for Python Spin App",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{container=\"hello-world-py\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage per Rust Spin App (MB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"hello-world-rust\"} / 1000 / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Seconds for Rust Spin App",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{container=\"hello-world-rust\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage per Go Spin App (MB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"hello-world-js\"}) / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Seconds for JS Spin App",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by() (container_cpu_usage_seconds_total{container=\"hello-world-js\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Constant VUs Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "90th Percentile HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, k6_http_req_duration_seconds{test_name=\"constant-vus\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile HTTP Request Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(k6_http_req_duration_seconds{test_name=\"constant-vus\"}[$__rate_interval])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Sent in 30s",
   "type": "gauge",
   "description": "With 0.1s delay between requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_reqs_total{test_name=\"constant-vus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_vus{test_name=\"constant-vus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Density Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "90th Percentile HTTP Request Duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "avg by(number_of_apps) (histogram_quantile(0.9, k6_http_req_duration_seconds{test_name=\"density\"})) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ramping Request Rate (by increasing VUs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }
  },
  {
   "title": "75th Percentile HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(k6_http_req_duration_seconds{test_name=\"ramping-vus\"}[$__rate_interval])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual/Concurrent Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "k6_vus{test_name=\"ramping-vus\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}